// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bicwvwrzibtkknisgcst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpY3d2d3J6aWJ0a2tuaXNnY3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTk1NjYsImV4cCI6MjA2MzI3NTU2Nn0.QSY_IpmNgebYf3eEa5mOW0Q6IftF0YQzuB2Q3OLiMVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);